/*
* This file is automatically generated from https://i2cdevices.org/
*
* Generated 2025-07-10 09:16:41
*
* It's intended to be used by the Arduino I2C diagnostic tool at
* https://github.com/pe2mbs/Arduino-I2C-Diagnostic-Tool
*
* To update the known device list in the diagnostic tool,
* generate a new version of this file, copy it to the src
* directory and rebuild the tool.
*
* The MIT License (MIT)
* Copyright © 2025 Marc Bertens-Nguyen <m.bertens@pe2mbs.nl>
* 
* Permission is hereby granted, free of charge, to any person
* obtaining a copy of this software and associated documentation
* files (the “Software”), to deal in the Software without
* restriction, including without limitation the rights to use, copy,
* modify, merge, publish, distribute, sublicense, and/or sell copies
* of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions: The above
* copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
* BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
* ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
* CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*/
#include <avr/pgmspace.h>


const char device_reserved[] PROGMEM = "Reserved";


const char device_0c[] PROGMEM = "AK8975";
const char device_0d[] PROGMEM = "AK8975";
const char device_0e[] PROGMEM = "AK8975,IST-8310,MAG3110";
const char device_0f[] PROGMEM = "AK8975";
const char device_10[] PROGMEM = "LM25066,VEML6075,VEML7700,VML6075";
const char device_11[] PROGMEM = "LC709203F ,LM25066,SAA5243P/E,SAA5243P/H,SAA5243P/K,SAA5243P/L,SAA5246,Si4713";
const char device_12[] PROGMEM = "LM25066,PMSA003I,SEN-17374";
const char device_13[] PROGMEM = "LM25066,SEN-17374,VCNL40x0";
const char device_14[] PROGMEM = "LM25066";
const char device_15[] PROGMEM = "LM25066";
const char device_16[] PROGMEM = "LM25066";
const char device_17[] PROGMEM = "LM25066";
const char device_18[] PROGMEM = "47L04/47C04/47L16/47C16,COM-15093,LIS3DH,LSM303,MCP9808";
const char device_19[] PROGMEM = "COM-15093,LIS3DH,LSM303,MCP9808";
const char device_1a[] PROGMEM = "47L04/47C04/47L16/47C16,MCP9808";
const char device_1b[] PROGMEM = "MCP9808";
const char device_1c[] PROGMEM = "47L04/47C04/47L16/47C16,FXOS8700,MCP9808,MMA845x,SAA7706H";
const char device_1d[] PROGMEM = "ADXL345,FXOS8700,MCP9808,MMA845x";
const char device_1e[] PROGMEM = "47L04/47C04/47L16/47C16,FXOS8700,HMC5883,LSM303,LSM303,MCP9808";
const char device_1f[] PROGMEM = "FXOS8700,MCP9808";
const char device_20[] PROGMEM = "Chirp!,FXAS21002,HW-061,MA12070P,MCP23008,MCP23017,PCA6408A,PCF8574,PCF8575,TCA9554,XD8574A";
const char device_21[] PROGMEM = "FXAS21002,HW-061,MA12070P,MCP23008,MCP23017,PCA6408A,PCF8574,PCF8575,SAA4700,TCA9554,XD8574A";
const char device_22[] PROGMEM = "HW-061,MA12070P,MCP23008,MCP23017,PCA1070,PCF8574,PCF8575,TCA9554,XD8574A";
const char device_23[] PROGMEM = "BH1750FVI,HW-061,MA12070P,MCP23008,MCP23017,PCF8574,PCF8575,SAA4700,TCA9554,XD8574A";
const char device_24[] PROGMEM = "HW-061,MCP23008,MCP23017,PCD3311C,PCD3312C,PCF8574,PCF8575,TCA9554,XD8574A";
const char device_25[] PROGMEM = "HW-061,MCP23008,MCP23017,PCD3311C,PCD3312C,PCF8574,PCF8575,TCA9554,XD8574A";
const char device_26[] PROGMEM = "HW-061,MCP23008,MCP23017,PCF8574,PCF8575,TCA9554,XD8574A";
const char device_27[] PROGMEM = "HIH6130,HW-061,MCP23008,MCP23017,PCF8574,PCF8575,TCA9554,XD8574A";
const char device_28[] PROGMEM = "BNO055,CAP1188,DS1841,DS1881,DS3502,FS3000,MCP4532,PM2008";
const char device_29[] PROGMEM = "BNO055,CAP1188,DS1841,DS1881,DS3502,MCP4532,TCS34725,TSL2591,VL53L0x,VL6180X";
const char device_2a[] PROGMEM = "CAP1188,DS1841,DS1881,DS3502,MCP4532";
const char device_2b[] PROGMEM = "CAP1188,DS1841,DS1881,DS3502,MCP4532";
const char device_2c[] PROGMEM = "AD5248,AD5251,AD5252,CAP1188,CAT5171,DS1881,MCP4532";
const char device_2d[] PROGMEM = "AD5248,AD5251,AD5252,CAP1188,CAT5171,DS1881,MCP4532,ST25DV16K ";
const char device_2e[] PROGMEM = "AD5248,AD5251,AD5252,DS1881,LPS22HB,MCP4532";
const char device_2f[] PROGMEM = "AD5243,AD5248,AD5251,AD5252,DS1881,MCP4532";
const char device_30[] PROGMEM = "SAA2502";
const char device_31[] PROGMEM = "SAA2502";
const char device_32[] PROGMEM = "ZMOD4410,ZMOD4450";
const char device_33[] PROGMEM = "MLX90640,ZMOD4510";
const char device_36[] PROGMEM = "MAX17048,MAX17048 ";
const char device_38[] PROGMEM = "AHT10,AHT20,BMA150,FT6x06,PCF8574AP,RRH46410,SAA1064,SEN-15892,VEML6070";
const char device_39[] PROGMEM = "APDS-9960,PCF8574AP,SAA1064,TSL2561,VEML6070";
const char device_3a[] PROGMEM = "MLX90632,PCF8574AP,PCF8577C,SAA1064";
const char device_3b[] PROGMEM = "PCF8569,PCF8574AP,SAA1064";
const char device_3c[] PROGMEM = "PCF8569,PCF8574AP,PCF8578,SH1106,SSD1305,SSD1306";
const char device_3d[] PROGMEM = "PCF8574AP,PCF8578,SH1106,SSD1305,SSD1306";
const char device_3e[] PROGMEM = "BU9796,PCF8574AP";
const char device_3f[] PROGMEM = "PCF8574AP";
const char device_40[] PROGMEM = "HDC1080,HTU21D-F,HTU31D,INA219,INA260,LM25066,NE5751,PCA9685,PCF8574,Si7021,TDA8421,TDA9860,TEA6300,TEA6320,TEA6330,TMP006,TMP007";
const char device_41[] PROGMEM = "HTU31D,INA219,INA260,LM25066,NE5751,PCA9536,PCA9685,PCF8574,STMPE610,STMPE811,TDA8421,TDA8424,TDA8425,TDA8426,TDA9860,TMP006,TMP007";
const char device_42[] PROGMEM = "HDC1008,INA219,INA260,LM25066,PCA9685,PCF8574,TDA8415,TDA8417,TMP006,TMP007";
const char device_43[] PROGMEM = "HDC1008,INA219,INA260,LM25066,PCA9685,PCF8574,TMP006,TMP007";
const char device_44[] PROGMEM = "HS30xx,INA219,INA260,ISL29125,LM25066,PCA9685,PCF8574,SHT31,STMPE610,STMPE811,TDA4670,TDA4671,TDA4672,TDA4680,TDA4687,TDA4688,TDA4780,TDA8442,TMP006,TMP007";
const char device_45[] PROGMEM = "INA219,INA260,LM25066,PCA9685,PCF8574,SHT31,TDA7433,TDA8376,TMP006,TMP007";
const char device_46[] PROGMEM = "INA219,INA260,LM25066,PCA9685,PCF8574,TDA8370,TDA9150,TMP006,TMP007";
const char device_47[] PROGMEM = "INA219,INA260,LM25066,PCA9685,PCF8574,TMP006,TMP007";
const char device_48[] PROGMEM = "ADS1015,ADS1115,ADS7828,INA219,INA260,LM75b,PCA9685,PCF8574,PN532,STDS75,TMP102";
const char device_49[] PROGMEM = "ADS1015,ADS1115,ADS7828,AS7262,INA219,INA260,LM75b,PCA9685,PCF8574,STDS75,TMP102,TSL2561";
const char device_4a[] PROGMEM = "ADS1015,ADS1115,ADS7828,CS43L22,INA219,INA260,LM75b,MAX44009,PCA9685,PCF8574,STDS75,TMP102";
const char device_4b[] PROGMEM = "ADS1015,ADS1115,ADS7828,INA219,INA260,LM75b,MAX44009,PCA9685,PCF8574,STDS75,TMP102";
const char device_4c[] PROGMEM = "EMC2101,INA219,INA260,LM75b,PCA9685,PCF8574,STDS75";
const char device_4d[] PROGMEM = "INA219,INA260,LM75b,PCA9685,PCF8574,STDS75";
const char device_4e[] PROGMEM = "INA219,INA260,LM75b,PCA9685,PCF8574,STDS75";
const char device_4f[] PROGMEM = "INA219,INA260,LM75b,PCA9685,PCF8574,STDS75";
const char device_50[] PROGMEM = "47L04/47C04/47L16/47C16,AT24C02N,AT24C64,CAT24C512,FS1015,LM25066,MB85RC,PCA9685";
const char device_51[] PROGMEM = "AT24C02N,AT24C64,CAT24C512,LM25066,MB85RC,PCA9685,PCF8563,VCNL4200";
const char device_52[] PROGMEM = "47L04/47C04/47L16/47C16,APDS-9250,AT24C02N,AT24C64,CAT24C512,LM25066,MB85RC,Nunchuck controller,PCA9685,SI1133";
const char device_53[] PROGMEM = "ADXL345,AT24C02N,AT24C64,CAT24C512,LM25066,MB85RC,PCA9685,ST25DV16K ";
const char device_54[] PROGMEM = "47L04/47C04/47L16/47C16,AT24C02N,AT24C64,CAT24C512,HS40xx,LM25066,MB85RC,PCA9685";
const char device_55[] PROGMEM = "AT24C02N,AT24C64,CAT24C512,D7S,LM25066,MAX30101,MB85RC,PCA9685,SI1133";
const char device_56[] PROGMEM = "47L04/47C04/47L16/47C16,AT24C02N,AT24C64,CAT24C512,LM25066,MB85RC,PCA9685";
const char device_57[] PROGMEM = "AT24C02N,AT24C64,CAT24C512,LM25066,MAX3010x,MB85RC,PCA9685,ST25DV16K ";
const char device_58[] PROGMEM = "LM25066,PCA9685,SGP30,TPA2016";
const char device_59[] PROGMEM = "LM25066,PCA9685,SGP40";
const char device_5a[] PROGMEM = "CCS811,CCS811,DRV2605,LM25066,MLX90614,MPR121,PCA9685";
const char device_5b[] PROGMEM = "CCS811,CCS811,MPR121,PCA9685";
const char device_5c[] PROGMEM = "AM2315,AM2320,BH1750FVI,MPR121,PCA9685";
const char device_5d[] PROGMEM = "MPR121,PCA9685,SFA30";
const char device_5e[] PROGMEM = "PCA9685";
const char device_5f[] PROGMEM = "HTS221,PCA9685";
const char device_60[] PROGMEM = "ATECC508A,ATECC608A,MCP4725A0,MCP4725A1,MCP4728,MPL115A2,MPL3115A2,PCA9685,SAB3035,SAB3037,SI1132,Si1145,Si5351A,TEA5767,TSA5511";
const char device_61[] PROGMEM = "MCP4725A0,MCP4725A1,MCP4728,PCA9685,SAB3035,SAB3037,SCD30,Si5351A,TEA6100,TSA5511";
const char device_62[] PROGMEM = "MCP4725A1,MCP4728,PCA9685,SAB3035,SAB3037,SCD40,SCD40-D-R2,SCD41,TSA5511,UMA1014T";
const char device_63[] PROGMEM = "MCP4725A1,MCP4728,PCA9685,SAB3035,SAB3037,Si4713,TSA5511,UMA1014T";
const char device_64[] PROGMEM = "MCP4725A1,MCP4725A2,MCP4728,PCA9685";
const char device_65[] PROGMEM = "MCP4725A1,MCP4725A2,MCP4728,PCA9685";
const char device_66[] PROGMEM = "IS31FL3731,LTC4151,MCP4725A1,MCP4725A3,MCP4728,PCA9685";
const char device_67[] PROGMEM = "LTC4151,MCP4725A1,MCP4725A3,MCP4728,PCA9685";
const char device_68[] PROGMEM = "AMG8833,BQ32000,DS1307,DS1371,DS3231,ICM-20948,ITG3200,LTC4151,MCP3422,MPU6050,MPU-9250,MPU-9250,PCA9685,PCF8523,PCF8573,WITTY PI 3";
const char device_69[] PROGMEM = "AMG8833,ICM-20948,ITG3200,LTC4151,MAX31341,MPU6050,MPU-9250,PCA9685,PCF8573,RRH62000,SPS30,WITTY PI 3";
const char device_6a[] PROGMEM = "L3GD20H,LTC4151,PCA9685,PCF8573";
const char device_6b[] PROGMEM = "L3GD20H,LTC4151,PCA9685,PCF8573";
const char device_6c[] PROGMEM = "LTC4151,PCA9685";
const char device_6d[] PROGMEM = "LTC4151,PCA9685";
const char device_6e[] PROGMEM = "LTC4151,PCA9685";
const char device_6f[] PROGMEM = "LTC4151,MCP7940N,PCA9685";
const char device_70[] PROGMEM = "HT16K33,PCA9541,PCA9685,SHTC3,TCA9548,TCA9548A,XD8574";
const char device_71[] PROGMEM = "HT16K33,PCA9541,PCA9685,TCA9548,TCA9548A,XD8574";
const char device_72[] PROGMEM = "HT16K33,PCA9541,PCA9685,TCA9548,TCA9548A,XD8574";
const char device_73[] PROGMEM = "HT16K33,PCA9541,PCA9685,TCA9548,TCA9548A,XD8574";
const char device_74[] PROGMEM = "HT16K33,PCA9539,PCA9541,PCA9685,TCA9548,TCA9548A,XD8574";
const char device_75[] PROGMEM = "HT16K33,PCA9539,PCA9541,PCA9685,TCA9548,TCA9548A,XD8574";
const char device_76[] PROGMEM = "BME280,BME680,BME688,BMP280,HT16K33,MS5607,MS5611,PCA9539,PCA9541,PCA9685,SPL06-007,TCA9548,TCA9548A,XD8574";
const char device_77[] PROGMEM = "BMA180,BME280,BME680,BME688,BMP085,BMP180,BMP280,HT16K33,IS31FL3731,MS5607,MS5611,PCA9539,PCA9541,PCA9685,SPL06-007,TCA9548,TCA9548A,XD8574";
const char device_78[] PROGMEM = "PCA9685";
const char device_79[] PROGMEM = "PCA9685";
const char device_7a[] PROGMEM = "PCA9685";
const char device_7b[] PROGMEM = "PCA9685";
const char device_7c[] PROGMEM = "PCA9685";
const char device_7d[] PROGMEM = "PCA9685";
const char device_7e[] PROGMEM = "PCA9685";
const char device_7f[] PROGMEM = "PCA9685";




typedef struct
{
    uint8_t     id;
    const char* devices;    
} I2C_DEVICE;

const I2C_DEVICE I2CTable[] PROGMEM = {
    { 0x00,  device_reserved },
    { 0x01,  device_reserved },
    { 0x02,  device_reserved },
    { 0x03,  device_reserved },
    { 0x04,  device_reserved },
    { 0x05,  device_reserved },
    { 0x06,  device_reserved },
    { 0x07,  device_reserved },
    { 0x08,  device_reserved },
    { 0x09,  device_reserved },
    { 0x0A,  device_reserved },
    { 0x0B,  device_reserved },
    { 0x0C,  device_0c },
    { 0x0D,  device_0d },
    { 0x0E,  device_0e },
    { 0x0F,  device_0f },
    { 0x10,  device_10 },
    { 0x11,  device_11 },
    { 0x12,  device_12 },
    { 0x13,  device_13 },
    { 0x14,  device_14 },
    { 0x15,  device_15 },
    { 0x16,  device_16 },
    { 0x17,  device_17 },
    { 0x18,  device_18 },
    { 0x19,  device_19 },
    { 0x1A,  device_1a },
    { 0x1B,  device_1b },
    { 0x1C,  device_1c },
    { 0x1D,  device_1d },
    { 0x1E,  device_1e },
    { 0x1F,  device_1f },
    { 0x20,  device_20 },
    { 0x21,  device_21 },
    { 0x22,  device_22 },
    { 0x23,  device_23 },
    { 0x24,  device_24 },
    { 0x25,  device_25 },
    { 0x26,  device_26 },
    { 0x27,  device_27 },
    { 0x28,  device_28 },
    { 0x29,  device_29 },
    { 0x2A,  device_2a },
    { 0x2B,  device_2b },
    { 0x2C,  device_2c },
    { 0x2D,  device_2d },
    { 0x2E,  device_2e },
    { 0x2F,  device_2f },
    { 0x30,  device_30 },
    { 0x31,  device_31 },
    { 0x32,  device_32 },
    { 0x33,  device_33 },
    { 0x36,  device_36 },
    { 0x38,  device_38 },
    { 0x39,  device_39 },
    { 0x3A,  device_3a },
    { 0x3B,  device_3b },
    { 0x3C,  device_3c },
    { 0x3D,  device_3d },
    { 0x3E,  device_3e },
    { 0x3F,  device_3f },
    { 0x40,  device_40 },
    { 0x41,  device_41 },
    { 0x42,  device_42 },
    { 0x43,  device_43 },
    { 0x44,  device_44 },
    { 0x45,  device_45 },
    { 0x46,  device_46 },
    { 0x47,  device_47 },
    { 0x48,  device_48 },
    { 0x49,  device_49 },
    { 0x4A,  device_4a },
    { 0x4B,  device_4b },
    { 0x4C,  device_4c },
    { 0x4D,  device_4d },
    { 0x4E,  device_4e },
    { 0x4F,  device_4f },
    { 0x50,  device_50 },
    { 0x51,  device_51 },
    { 0x52,  device_52 },
    { 0x53,  device_53 },
    { 0x54,  device_54 },
    { 0x55,  device_55 },
    { 0x56,  device_56 },
    { 0x57,  device_57 },
    { 0x58,  device_58 },
    { 0x59,  device_59 },
    { 0x5A,  device_5a },
    { 0x5B,  device_5b },
    { 0x5C,  device_5c },
    { 0x5D,  device_5d },
    { 0x5E,  device_5e },
    { 0x5F,  device_5f },
    { 0x60,  device_60 },
    { 0x61,  device_61 },
    { 0x62,  device_62 },
    { 0x63,  device_63 },
    { 0x64,  device_64 },
    { 0x65,  device_65 },
    { 0x66,  device_66 },
    { 0x67,  device_67 },
    { 0x68,  device_68 },
    { 0x69,  device_69 },
    { 0x6A,  device_6a },
    { 0x6B,  device_6b },
    { 0x6C,  device_6c },
    { 0x6D,  device_6d },
    { 0x6E,  device_6e },
    { 0x6F,  device_6f },
    { 0x70,  device_70 },
    { 0x71,  device_71 },
    { 0x72,  device_72 },
    { 0x73,  device_73 },
    { 0x74,  device_74 },
    { 0x75,  device_75 },
    { 0x76,  device_76 },
    { 0x77,  device_77 },
    { 0x78,  device_78 },
    { 0x79,  device_79 },
    { 0x7A,  device_7a },
    { 0x7B,  device_7b },
    { 0x7C,  device_7c },
    { 0x7D,  device_7d },
    { 0x7E,  device_7e },
    { 0x7F,  device_7f },
};

