/*
* This file is automatically generated from https://i2cdevices.org/
*
* Generated 2025-07-11 09:07:36
*
* It's intended to be used by the Arduino diagnostic tool at
* https://github.com/pe2mbs/Arduino-Diagnostic-Tool
*
* To update the known device list in the diagnostic tool,
* generate a new version of this file, copy it to the src
* directory and rebuild the tool.
*
* The MIT License (MIT)
* Copyright © 2025 Marc Bertens-Nguyen <m.bertens@pe2mbs.nl>
* 
* Permission is hereby granted, free of charge, to any person
* obtaining a copy of this software and associated documentation
* files (the “Software”), to deal in the Software without
* restriction, including without limitation the rights to use, copy,
* modify, merge, publish, distribute, sublicense, and/or sell copies
* of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions: The above
* copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
* BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
* ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
* CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*/
#ifndef __I2C_DEVICES__
#define __I2C_DEVICES__ 1

#include <avr/pgmspace.h>
#include <Arduino.h>
#include <Wire.h>
#include <LibPrintf.h>


typedef struct
{
    uint8_t     id;
    const char* devices;    
} I2C_DEVICE;

typedef unsigned char byte;

#define __version__     "1.0.8"


class I2C_devices
{
private:
    I2C_DEVICE              device;
    char*                   buffer;
public:
    I2C_devices();
    const char* getLabel( int address );
    void banner();
    void scan( void );
private:
    static const I2C_DEVICE I2CTable[ 128 ] PROGMEM;
};

#endif